[tool.ruff]
src = ["libs"]
line-length = 100
target-version = "py311"
include = ["*.py", "*.pyi", "**/pyproject.toml", "*.ipynb"]
lint.select = [
    "E",  # pycodestyle
    "F",  # pyflakes
    "UP", # pyupgrade
    # "D",   # pydocstyle
    "I",   # isort
    "PL",  # pylint
    "RUF", # ruff-specific
    "N",   # pep8-naming
    "C4",  # flake8-comprehensions
    "B",   # flake8-bugbear
    "PT",  # flake8-pytest-style
]
lint.ignore = [
    "F722",    # Syntax error in forward annotation
    "F821",
    "PLR0913",
]

[tool.ruff.per-file-ignores]
"*.ipynb" = ["F401"]
# "test_custom_list.py" = ["RUF005"]

[tool.ruff.isort]
known-first-party = ["libs.my_sac"]

[tool.pyright]
reportPrivateImportUsage = false
