[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
src = ["libs"]
line-length = 88
target-version = "py311"
include = ["*.py", "*.pyi", "**/pyproject.toml", "*.ipynb"]
select = [
    "E",  # pycodestyle
    "F",  # pyflakes
    "UP", # pyupgrade
    # "D",   # pydocstyle
    "I",   # isort
    "PL",  # pylint
    "RUF", # ruff-specific
    "N",   # pep8-naming
    "C4",  # flake8-comprehensions
    "B",   # flake8-bugbear
    "PT",  # flake8-pytest-style
]
ignore = [
    "F722",     # Syntax error in forward annotation
    "PLR0913",
]

# [tool.ruff.per-file-ignores]
# "test_custom_list.py" = ["RUF005"]

# [tool.ruff.isort]
# known-first-party = ["server", "client"]
